name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:frontend ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:backend ./backend


      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:backend
